### ISSUE TITLE
API Endpoint Review and Cleanup for /credentials

### ISSUE THREAD

**Issue by KDwevedi** [Unified-Learner-Passbook/Credential-MS#18]
## Description
Cleaning up and review of the APIs at the [/credentials path](https://github.com/Unified-Learner-Passbook/Credential-MS/blob/main/src/credentials/credentials.controller.ts#L59) is required wrt the [Sunbird RC Swagger docs](https://github.com/Sunbird-RC/sunbird-rc-core/blob/main/api-documentation/issue-api.yaml) along with an evaluation of APIs that are completely or partially unimplemented.

## APIs
1. **Obtain Credentials by Subject or Issuer**
Currently implemented [here](https://github.com/Unified-Learner-Passbook/Credential-MS/blob/288bd0911147da11712d00a3f9234c5050b7dc6a/src/credentials/credentials.controller.ts#L23).
The [request body implemented](https://github.com/Unified-Learner-Passbook/Credential-MS/blob/main/src/credentials/dto/getCredentialsBySubjectOrIssuer.dto.ts) differs from request body expected according to [RC Swagger Docs](https://github.com/Sunbird-RC/sunbird-rc-core/blob/f729f958a660606b0350a5ddbe66e0321a7c9ed4/api-documentation/issue-api.yaml#L100), as such the DTO may be needed to be updated.

2. **Obtain Credential by ID**
This API ([implemented here](https://github.com/Unified-Learner-Passbook/Credential-MS/blob/288bd0911147da11712d00a3f9234c5050b7dc6a/src/credentials/credentials.controller.ts#L28)) is currently bugged and returns only an empty array. 
The RC docs again stipulate additional header parameters [here](https://github.com/Sunbird-RC/sunbird-rc-core/blob/f729f958a660606b0350a5ddbe66e0321a7c9ed4/api-documentation/issue-api.yaml#L61) which are not being handled currently.

3. **Issue a Credential**
The [request body](https://github.com/Unified-Learner-Passbook/Credential-MS/blob/main/src/credentials/dto/issue-credential.dto.ts) currently takes in the entire credential schema when [RC docs](https://github.com/Sunbird-RC/sunbird-rc-core/blob/f729f958a660606b0350a5ddbe66e0321a7c9ed4/api-documentation/issue-api.yaml#L41) expect only a string.  

4. **Update Credential Status**
This [API endpoint](https://github.com/Unified-Learner-Passbook/Credential-MS/blob/288bd0911147da11712d00a3f9234c5050b7dc6a/src/credentials/credentials.controller.ts#L38) is currently [not implemented](https://github.com/Unified-Learner-Passbook/Credential-MS/blob/288bd0911147da11712d00a3f9234c5050b7dc6a/src/credentials/credentials.service.ts#L186).

5. **Derive a Credential**
This [API endpoint](https://github.com/Unified-Learner-Passbook/Credential-MS/blob/288bd0911147da11712d00a3f9234c5050b7dc6a/src/credentials/credentials.controller.ts#L53) to derive a credential is currently [not implemented](https://github.com/Unified-Learner-Passbook/Credential-MS/blob/288bd0911147da11712d00a3f9234c5050b7dc6a/src/credentials/credentials.service.ts#L259).

6. **Render a Credential**
This API is currently bugged (returns 500 on first call, but rendered PDF on the second). The current implementation also has other issues for which I'll create a dedicated issue soon.

## Tasks

- [x] Review and modify request body for API to Obtain Credentials by Subject or Issuer
- [x] Review and modify request body for API to Obtain Credential by ID
- [x] Review and modify request body for API to Issue a Credential
- [x] Fix the bug that returns an empty array for API to Obtain Credential by ID
- [x] Implement or discard API to Update Credential Status
- [x] Implement or discard API to Derive a Credential
- [x] Review and address the bug in Render Credential API

**Comment by techsavvyash** [comment]
All of these have been addressed and closed
