### ISSUE TITLE
Brush up verify endpoint

### ISSUE THREAD

**Issue by techsavvyash** [Unified-Learner-Passbook/Credential-MS#23]
## Description

There current implementation of `/verify` endpoint does not conform to the API spec given [here](https://github.com/Sunbird-RC/sunbird-rc-core/blob/main/api-documentation/issue-api.yaml) and hence needs to be updated.

## Tasks

- [x] Update the endpoint signature
- [x] Change the request method from `POST` to `GET`
- [x] Add checks as per the spec
- [x] update the return value of the endpoint
