### ISSUE TITLE
Brush up the return types of the Credential APIs

### ISSUE THREAD

**Issue by techsavvyash** [Unified-Learner-Passbook/Credential-MS#25]
## Description

Almost all the endpoints present in this repository are not returning the responses conforming to the spec given [here](https://github.com/Sunbird-RC/sunbird-rc-core/blob/main/api-documentation/issue-api.yaml). Proper cleanup of the return types is required to be done to make the APIs compliant with SunbirdRC.

## Tasks

- [x] Update the Signature of the searchByIssuerOrSubject 
- [x] update the returned object for the following endpoints
    - [x] `POST /credentials/search` for searchByIssuerOrSubject
    - [x] `GET /crdentials/{id}`
