### ISSUE TITLE
API Cleanup

### ISSUE THREAD

**Issue by techsavvyash** [Unified-Learner-Passbook/Credential-MS#27]
## Description

The following issues need to be closed to have clean and compliant APIs as per the spec [SunbirdRC Spec](https://github.com/Sunbird-RC/sunbird-rc-core/blob/main/api-documentation/issue-api.yaml)

## Issue List

- [x] Unified-Learner-Passbook/Credential-MS#23
- [x] Unified-Learner-Passbook/Credential-MS#24
- [x] Unified-Learner-Passbook/Credential-MS#25
- [x] Unified-Learner-Passbook/Credential-MS#18
